### ISSUE TITLE
Allow nested groups

### ISSUE THREAD

**Issue by jaulz** [dlevs/vscode-regex-robin#2]
Sorry to create one more issue but I just thought that it would be cool to have nested groups. From an API perspective `group` could also receive an array and based on that the tree could be generated. In my case I would group the matched patterns first by a constant name and on a second level by the method name they appeared in.

**Comment by dlevs** [comment]
Good idea! I've [implemented](https://github.com/dlevs/vscode-regex-robin/commit/c15ee3cbf27f00df2c92b985a8e973b563a0b7cc) and published it - give it a go and let me know what you think.

**Comment by jaulz** [comment]
Wow, great, that was fast 😊  Thanks a lot, it's working!
