### ISSUE TITLE
[Feature Request] allow inlineReplacement to not expand on select

### ISSUE THREAD

**Issue by reececomo** [dlevs/vscode-regex-robin#4]
Heya, first off Regex Robin is awesome, thank you for the fantastic plugin!

We've got one project where every function and property has a big fat prefix on it, and we're able to hide it using `inlineReplacement`. Would it be possible to take it a step further and be able to prevent expanding the selected line?

Or only expand when cmd+click etc.

<img width="667" alt="Screenshot 2023-07-06 at 6 36 38 pm" src="https://github.com/dlevs/vscode-regex-robin/assets/7390781/401d6b45-62dc-4a5f-8e45-47798d24389d">
<img width="713" alt="Screenshot 2023-07-06 at 6 36 23 pm" src="https://github.com/dlevs/vscode-regex-robin/assets/7390781/a87001a5-e826-4147-9e8d-ac4c3896f483">

**Comment by dlevs** [comment]
Hi! That seems possible. I imagine it could lead to a confusing experience, but you could experiment and see if it works.

You can set this `showInlineReplacement` variable to always be `true`: https://github.com/dlevs/vscode-regex-robin/blob/d6f39731b4a13b951d04bf84124b51039bfa2081/src/decoration.ts#L56

That should give you what you want. I'm on a mobile at the moment, so have not tried it myself. Try it out and see if it works as you need. If it works well, I'd accept a PR that extends the config for this. Maybe the object form of `inlineReplacement` could have a new property for changing when the inline replacement shows/hides.

**Comment by reececomo** [comment]
Closed as completed? 😆

**Comment by dlevs** [comment]
Haha, no. 😉  Closed as inactive since you didn't reply to my last message.

I don't have capacity to add features I don't need, but will happily review and merge PRs.

**Comment by reececomo** [comment]
Haha ye I know

![Screenshot 2024-02-12 130422](https://github.com/dlevs/vscode-regex-robin/assets/7390781/e930cbde-9875-4322-be5b-81e99d830508)

All good! Totally understand, and didn't mean to ghost you 😆

**Comment by dlevs** [comment]
Ahhh, got you. Thanks for pointing that out!
