### ISSUE TITLE
[SOLVED]: Invalid flags: dg

### ISSUE THREAD

**Issue by AlexVipond** [dlevs/vscode-regex-robin#6]
This error appears when you install Regex Robin and another extension called Todo Tree at the same time. This is reportedly because Todo Tree ships a `String.prototype.matchAll` polyfill that breaks other extensions that rely on the native implementation.

To fix, uninstall Todo Tree and reload the editor window. Regex Robin's example config shows how to recreate most of what Todo Tree offers.

**Comment by dlevs** [comment]
Glad you found a solution. Funnily enough, I had "Todo Tree" installed when I was developing this and faced the exact same issue. I remember how frustrating that was, so I've [added this to the README](https://github.com/dlevs/vscode-regex-robin/pull/7).

Thanks for sharing. 🙂
