### ISSUE TITLE
Sorting of matches in tree view according to their position in the file

### ISSUE THREAD

**Issue by musketon-be** [dlevs/vscode-regex-robin#9]
Dear developer,

First of all I really like the extension! It works very well and I didn't really find a similar tool as good as this one.
But I do miss one feature/setting though... Currently, from what I could see, the matches are presented alphabetically in the tree view (within a given group, and the groups themselves are then also ordered alphabetically). This is nice, but often I would rather want to see the matches presented according to the sequence they occur in the file.

Let's say that I have a regex to filter on `ID` and I have the following file:
```
ID="2";
ID="1";
ID="3";
```

Then the tree view for the file looks like:
```
ID="1";
ID="2";
ID="3";
```

I would rather want to see a tree view like this:
```
ID="2";
ID="1";
ID="3";
```

Is this currently already possible with one or another setting that I am not yet aware of?

If not, then I think it would be a nice feature to include.
Listing the matches according to their position in the file within their group only would be very nice.

To extend somewhat further, it might also be nice to have a flat list in the tree view, simply listing all the matches in the same sequence as in the file (omitting the groups where they belong to). This is for me less important though.

Looking forward to your reply and thanks in advance!

**Comment by dlevs** [comment]
Hi! I'm glad you like the extension. :)

Your suggestion sounds good.

I won't have the time to make this change, but I'd happily accept a pull request that makes sorting optional. The same for the flat tree view - that's a good idea. It's all in `tree.ts`.

The sorting is done in this code:

```ts
  const sortedDirectories = sortBy(children, ({ label }) => label);
  const sortedItems = sortBy(tree.items, ({ label }) => label);
```

So you could just skip that part based on the new setting.

**Comment by ChristinWhite** [comment]
I'm so glad I found this extension, it's absolutely fantastic and just what I needed! I did have the same request though. Sounds like I may need to find some time to figure out how extensions work and make that tweak if @musketon-be doesn't want to jump in to it.

**Comment by musketon-be** [comment]
Just to give an update: I am working on it. It took some time as I am also new in extension development. But currently I have it working on my side. Next step is to finish it properly and prepare pull request. I hope to finish it in the next days.

**Comment by musketon-be** [comment]
@dlevs I made the changes and I tried to put them on a new branch, but it seems I don't have permissions to create a new branch. Is it ok that I simply drop the files here such that you can include them in the repo?

See attached zip:
- package.json: properties added to describe the configuration settings (+ many other changes that were added automatically)
- tree.ts: changed behavior based on the configuration settings (see below)
- package-lock.json: many changes added automatically (I suppose it is due to 'npm update' that I did)

As for the changes themselves: I added a few extra configuration options:
- items in tree view displayed in sequential/alphabetical order (covering this issue)
- initial tree view collapsed/expanded
- filename printing in items

[config_update.zip](https://github.com/dlevs/vscode-regex-robin/files/14145183/config_update.zip)

**Comment by dlevs** [comment]
Nice, thanks @musketon-be! I've [worked those changes into a v0.1.8](https://github.com/dlevs/vscode-regex-robin/commit/5555eb31124cae218f626c5847ca6cad1fe567ae), which is published now.

**Comment by ChristinWhite** [comment]
@musketon-be Any chance I could see an example config with those rules? I'm having trouble figuring out exactly where to add them.

**Comment by musketon-be** [comment]
@dlevs Thanks for taking the time to integrate my changes!

@ChristinWhite I think there is something wrong with newest release...

When I was updating/checking the extension, I got this in my settings UI:
![image](https://github.com/dlevs/vscode-regex-robin/assets/157758562/2069b454-ecfa-49f0-9802-98bfef2a751d)

When I try now with v0.1.8, I only get this:
![image](https://github.com/dlevs/vscode-regex-robin/assets/157758562/f6e5dede-981b-47a7-aad7-6181590af75f)

Maybe @dlevs has an idea what could be wrong?

**Comment by dlevs** [comment]
Hi @ChristinWhite @musketon-be ,

I changed the properties a little from the ones in the PR, so they look like this:
![Screenshot 2024-02-15 at 09 10 15](https://github.com/dlevs/vscode-regex-robin/assets/7463091/3070ef29-9c42-4d6b-a695-754661e07c78)

```json
  "regexrobin.tree": {
    "expanded": true,
    "includeFilenames": false,
    "sort": true
  },
```

**Comment by dlevs** [comment]
I didn't realise the docs that get generated from the package.json settings are so useless. 🙈

![Screenshot 2024-02-15 at 09 13 03](https://github.com/dlevs/vscode-regex-robin/assets/7463091/b48f6ad6-5f2e-4653-b44b-6a85d1b9e313)

I'll need to document these in the README at some point...

**Comment by musketon-be** [comment]
@dlevs Indeed, using these settings in my settings file it works fine! Good enough for me at the moment. Documentation can come later :-)
```
  "regexrobin.tree": {
    "expanded": true,
    "includeFilenames": false,
    "sort": true
  },
```

Thanks for your support!

**Comment by musketon-be** [comment]
@dlevs Meanwhile I used v0.1.8 already a lot. Just to let you know that it works well and I really like the extension now! :-)

**Comment by dlevs** [comment]
> @dlevs Meanwhile I used v0.1.8 already a lot. Just to let you know that it works well and I really like the extension now! :-)

Glad to hear! 😁
